# Generated by Django 3.2.21 on 2024-01-04 13:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('botid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('botname', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='BotMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('botid', models.UUIDField()),
                ('username', models.CharField(max_length=100)),
                ('chatid', models.CharField(max_length=32)),
                ('message', models.TextField()),
                ('isgroup', models.BooleanField()),
                ('seen_cnt', models.IntegerField(default=0)),
                ('read_cnt', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
