# Generated by Django 3.2.21 on 2024-01-04 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bot',
            old_name='botid',
            new_name='id',
        ),
    ]
