# Generated by Django 3.2.21 on 2024-01-04 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_botid_bot_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bot',
            old_name='botname',
            new_name='name',
        ),
    ]
