# Generated by Django 3.2.21 on 2024-01-04 16:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_botname_bot_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='botmessage',
            name='botid',
            field=models.CharField(max_length=32),
        ),
    ]
