# Generated by Django 3.2.21 on 2024-01-06 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20240104_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botmessage',
            name='username',
        ),
    ]
