# Generated by Django 3.2.21 on 2024-01-07 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_botmessage_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatid', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=100)),
                ('participants_size', models.IntegerField()),
                ('participants', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
