# Generated by Django 4.1 on 2024-01-30 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_grouplog_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
                ('chatid', models.CharField(max_length=32)),
                ('botid', models.CharField(max_length=32)),
            ],
        ),
    ]
