# Generated by Django 4.1 on 2024-01-30 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_grouptags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroupTags',
            new_name='GroupTag',
        ),
    ]
