# Generated by Django 4.1 on 2024-02-12 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rename_grouptags_grouptag'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='type',
            field=models.CharField(choices=[('semi-active', 'Semi-Active'), ('active', 'Active')], default='semi-active', max_length=32),
        ),
    ]
