# Generated by Django 4.1 on 2024-03-17 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0010_bot_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="BotMessageTrigger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("botid", models.CharField(max_length=32)),
                ("trigger", models.CharField(max_length=100)),
                ("response", models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name="bot",
            name="botStarted",
            field=models.IntegerField(default=0),
        ),
    ]
